/** @type {import('tailwindcss').Config} */

// Every colour family below resolves through a CSS variable defined in
// src/styles/tokens.css (generated by tools/gen-tokens.mjs), which ships a
// light ramp on :root and a dark ramp on .dark. Utilities are therefore
// mode-agnostic: `bg-slate-50` is a near-white panel in light mode and a
// lifted near-black panel in dark mode, so pages need no `dark:` variants.
//
// The channels are stored space-separated (`248 250 252`) rather than as hex
// so Tailwind's `<alpha-value>` slot keeps working — `bg-brand-500/40` and
// friends still compose.
const ramp = name =>
  Object.fromEntries(
    [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950].map(shade => [
      shade,
      `rgb(var(--c-${name}-${shade}) / <alpha-value>)`,
    ]),
  )

const token = name => `rgb(var(--t-${name}) / <alpha-value>)`

export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Themed ramps — same class names as before, now mode-aware.
        slate:   ramp('slate'),
        brand:   ramp('brand'),
        sun:     ramp('sun'),
        red:     ramp('red'),
        orange:  ramp('orange'),
        amber:   ramp('amber'),
        yellow:  ramp('yellow'),
        green:   ramp('green'),
        emerald: ramp('emerald'),
        teal:    ramp('teal'),
        blue:    ramp('blue'),
        purple:  ramp('purple'),
        pink:    ramp('pink'),

        // Semantic surfaces and text. Prefer these over raw ramp shades for
        // anything structural — they carry intent, not just a colour.
        surface:          token('surface'),
        'surface-sunken':  token('surface-sunken'),
        elevated:         token('elevated'),
        'elevated-hover':  token('elevated-hover'),
        ink:              token('ink'),
        'ink-muted':       token('ink-muted'),
        'ink-subtle':      token('ink-subtle'),
        line:             token('line'),
        'line-strong':     token('line-strong'),
        // Text/icon colour to sit on a saturated accent fill. White in light
        // mode, near-black in dark mode — never hardcode `text-white` on an
        // accent background, it inverts wrong.
        'on-accent':       token('on-accent'),
        // Terminal-style output panels stay dark in both modes, so these do
        // not flip — see CODE_FIXED in tools/gen-tokens.mjs.
        'code-bg':         token('code-bg'),
        'code-ink':        token('code-ink'),
        'code-muted':      token('code-muted'),
        'code-accent':     token('code-accent'),
        'code-line':       token('code-line'),
      },
      fontFamily: {
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        display: ['"Space Grotesk"', '"DM Sans"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Fira Code', 'monospace'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
        // Editorial display sizes for hero/section type.
        'display-sm': ['2.5rem',  { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display-md': ['3.5rem',  { lineHeight: '0.98', letterSpacing: '-0.03em' }],
        'display-lg': ['4.75rem', { lineHeight: '0.94', letterSpacing: '-0.035em' }],
      },
      boxShadow: {
        // Purple-tinted lift in light mode, plain depth in dark mode where a
        // coloured shadow reads as smudge.
        'lift':    'var(--shadow-lift)',
        'lift-sm': 'var(--shadow-lift-sm)',
      },
      keyframes: {
        'pop-once': {
          '0%':   { opacity: 0, transform: 'scale(0.5)' },
          '60%':  { opacity: 1, transform: 'scale(1.15)' },
          '100%': { opacity: 1, transform: 'scale(1)' },
        },
      },
      animation: {
        'pop-once': 'pop-once 0.4s cubic-bezier(0.34,1.56,0.64,1) both',
      },
    },
  },
  plugins: [],
}
